// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDarIihCevNnyQEt2lZ-3E7HCFH5MIijLU',
    appId: '1:1050301262511:android:0a72a27ac94485b021c25a',
    messagingSenderId: '1050301262511',
    projectId: 'stargazer-6eae6',
    databaseURL: 'https://stargazer-6eae6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stargazer-6eae6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVA3u8Yp_vzLqRiuEk9554X6hcDZIjoac',
    appId: '1:1050301262511:ios:8da29c362df8a37d21c25a',
    messagingSenderId: '1050301262511',
    projectId: 'stargazer-6eae6',
    databaseURL: 'https://stargazer-6eae6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stargazer-6eae6.firebasestorage.app',
    iosClientId: '1050301262511-9e9plcpco9tcvn8310rfjeuhjg09oqob.apps.googleusercontent.com',
    iosBundleId: 'com.example.stargazer',
  );
}
